/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.geoquest.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int btnTourInfo=0x7f050003;
        public static final int btnViewTours=0x7f050002;
        public static final int idtour=0x7f050000;
        public static final int name=0x7f050001;
    }
    public static final class layout {
        public static final int all_tours=0x7f030000;
        public static final int list_item=0x7f030001;
        public static final int main_screen=0x7f030002;
        public static final int tour_info=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
